name: spotify
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  appwrite: ^8.1.0
  audio_video_progress_bar:
  flutter_animate: 
  gap: 
  provider: 
  tab_container: 
  country_flags: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
      - images/
  fonts:
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand-Bold.ttf
          weight: 700
        - asset: fonts/Quicksand-Light.ttf
          weight: 300
        - asset: fonts/Quicksand-Medium.ttf
          weight: 400
        - asset: fonts/Quicksand-Regular.ttf
          weight: 500
        - asset: fonts/Quicksand-SemiBold.ttf
          weight: 600